name: riverpod_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.10
  go_router: ^10.0.0
  hooks_riverpod: ^2.4.10
  random_name_generator: ^1.1.0
  riverpod_annotation: ^2.3.4
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:

  uses-material-design: true
